### ISSUE TITLE
Rotation parameters are not configureable

### ISSUE THREAD

**Issue by yechiel-optimalq** [omrikiei/logging_s3_handler#1]
Allow initialization of the relevant parameters:

DEFAULT_CHUNK_SIZE = 5 * 1024 ** 2  # 5 MB
DEFAULT_ROTATION_TIME_SECS = 12 * 60 * 60  # 12 hours
MAX_FILE_SIZE_BYTES = 100 * 1024 ** 2  # 100 MB

**Comment by omrikiei** [comment]
Hello Yechiel,
Those default values can(and should) be overridden in the instantiation of the handler class
`handler = handler = S3Handler(filename, bucket, key_id, secret, chunk_size=CUSTOM_CHUNK_SIZE,
time_rotation=CUSTOM_ROTATION_TIME_SECS, max_file_size_bytes=CUSTOM_MAX_FILE_SIZE, encoder='utf-8')`
Regarding the rotation interval and max bytes, I will feature it soon as the logic is not yet coded and tested - once I do that I will make sure that examples are added to the readme file..
I appreciate your feedback,
Omri

**Comment by omrikiei** [comment]
Sorted out in version 0.1.2
